module.exports = {
  "Influenza": ["high fever (>100.4 F)",
  "sore throat",
  "chills",
  "headache",
  "body aches",
   "dry cough",
    "nasal congestion",
    "increased sweating",
     "fatigue"
   ],
    "Common Cold": ["cough",
    "fatigue",
     "low fever (<100.4 F)",
     "nasal congestion",
     "runny nose",
     "sneezing",
     "sore throat"],
     
    "Pneumonia": ["chest pain while breathing", "chills", "confusion (elders)", "cough with phlegm", "diarrhoea", "fatigue", "high fever (>100.4 F)", "increased sweating", "lower body temp (elders)", "nausea", "shaking", "shortness of breath", "vomiting"],
    "Diarrhoea": ["abdominal cramps", "abdominal pain (mild)", "bloating", "blood in stool", "low fever (<100.4 F)", "mucus in stool", "nausea", "watery stool"],
    "Indigestion": ["bloating in upper abdominal", "burnig in upper abdominal", "discomfort in upper abdominal", "early feeling of fullness while eating", "nausea"],
    "Intestinal Gas": ["abdominal cramps", "abdominal pain (mild)", "bloating", "burping", "increased size of abdomen", "knotted feeling in the abdomen", "passing gas"],
    "Constipation": ["difficulty passing stool","straining when passing stool","passing less stool than usual","lumpy, dry and hard stool","pain and cramping in stomach","feeling bloated"],
    "Malaria": ["abdominal pain (mild)", "chest pain", "chills", "cough", "fatigue", "headache", "high fever (>100.4 F)", "increased sweating", "muscle pain", "nausea", "vomiting"],
    "Dengue": ["anxiety", "bleeding in gums", "bleeding in nose", "blood in stool", "blood in urine", "blood in vomit", "bone pain", "cold skin", "difficulty breathing", "fatigue", "headache", "irritability", "joint pain", "muscle pain", "nausea", "pain behind the eyes", "rash on the face", "swelling in glands", "vomiting (persistent)"],
    "Hypertension": ["blood in urine", "chest pain", "confusion (elders)", "difficulty breathing", "fatigue", "headache (severe)", "irregular heartbeat", "pounding in chest", "pounding in neck", "pounding in ears", "vision problem"],
    "Stress": ["anxiety", "chest pain", "fatigue", "headache", "irritability", "muscle pain", "restlessness", "sleeping disorder"],
    "Panic Attacks": ["abdominal cramps", "chest pain", "chills", "difficulty breathing", "fear of loss", "headache", "increased sweating", "nausea", "numbness", "rapid heart rate", "sense of danger", "shaking"],
    "Chicken Pox": ["crusts", "fatigue", "fluid filled blisters", "headache", "high fever (>100.4 F)", "loss of appetite", "raised pink or red bumps", "scabs"],
    "Measles": ["conjuctivitis", "dry cough", "low fever (<100.4 F)", "runny nose", "skin rash with large blotches", "sore throat", "white spots with bluish-white centers on a red background in the mouth"],
    "Mumps": ["fatigue", "headache", "loss of appetite", "low fever (<100.4 F)", "muscle pain", "pain in cheeks", "pain while chewing", "swelling in cheeks"],
    "Cellulitis": ["blisters", "low fever (<100.4 F)", "red area of skin that keeps expanding", "red spots", "skin dimpling", "swelling of red area of skin"],
    "Dermatitis": ["dry skin", "flaky skin", "itching (severe)", "oozing blisters", "scaly skin", "sensitivity to sun", "skin burning", "skin redness", "swelling in face", "swelling in groin", "swelling in eyes"],
    "Acne": ["blackheads", "large lumps under the skin", "pimples", "pus filled lumps under skin", "raised pink or red bumps", "whiteheads"],
    "Insomnia": ["anxiety", "daytime tiredness or sleepiness", "depression", "difficulty falling asleep at night", "inability to concentrate and focus", "increased erros or accidents", "not feeling well-rested after night's sleep", "waking up during night", "waking up too early"],
    "Sleep Apnea": ["awakenig with dry mouth", "daytime tiredness or sleepiness", "difficulty staying asleep", "gasping for air during sleep", "inability to concentrate and focus", "intervals in which one stops breathing during sleep", "irritability", "loud snoring", "morning headache"],
    "Hyperthyroidism": ["brittle hair", "elevated blood pressure", "hand tremors", "inability to concentrate and focus", "increased sweating", "irregular menstrual cycle (women)", "low tolerence to heat", "rapid heart rate", "restlessness", "sleeping disorder", "swelling glands", "weakness", "weight loss"],
    "Hypothyroidism": ["body aches", "decreased sweating", "depression", "dry and thinner hair", "dry skin", "elevated blood cholesterol", "fatigue", "impaired memory", "irregular menstrual cycle (women)", "joint pain", "muscle pain", "muscle weakness", "slow heart rate", "weight gain"],
    "Kidney Stones": ["abdominal pain (severe)", "blood in urine", "chills", "cloudy and smelly urine", "decreased flow of urine", "high fever (>100.4 F)", "nausea", "pain in the back", "pain in the side of the body", "pain or burnig during urination", "very frequent and urgent need to pee", "vomiting"],
    "Urinary Tract Infection": ["chills", "cloudy and smelly urine", "dark bloody or strange urine", "daytime tiredness or sleepiness", "low fever (<100.4 F)", "nausea", "pain in lower belly", "pain in the back", "pain in lower back", "pain or buring during urination", "very frequent and urgent need to pee", "vomiting"]
}
