module.exports = {
  "Common Cold": ["Do salt water gargle", "Drink a lot of fluid", "Take a warm bath", "Drink Ginger Tea"],

  "Influenza":["Drinking Water and other fluids.",
  "Getting plenty of rest.It's a must.",
  "Drinking warm Broth/Soup/Herbal Tea.",
  "Increasing your zinc intake(Eat lentils,shellfish,dairy,eggs,nuts,beans).",
  "Rinsing with Salt Water.",
  "Applying essential Oils."],

  "Pneumonia":["A","B","C"],

  "Diarrhoea": ["Drink plenty of fluids to avoid dehydration", "Avoid milk as it can make diarrhoea worst",
    "Sport Beverages (eg. Gatorade or Powerade) can be beneficial", "Avoid greasy or fatty foods",
    "Follow BRAT diet(ie. Bananas, Rice, Apple sauce, Toast)"],

  "Indigestion": ["Drink a cup of peppermint tea or suck a peppermint candy after meals",
    "Drink chamomile tea as it can ease gut discomfort and relieve indigestion",
    "Drink apple cider vinegar by adding one to two teaspoons of it in a cup of water",
    "Drink a cup of ginger tea as needed to soothe you stomach and get rid of indigestion",
    "Put half teaspoon of crushed fennel seed in water and boil it for 10 minutes and drink",
    "Drink baking soda solution", "Mix a tablespoon of lemon juice in hot or warm water and drink a few minutes before eating"],

  "Intestinal Gas": ["Exercise can help release trapped gas and gas pain(try walking after meals to avoid gas)",
    "Lactase supplements may help your body to digest lactose", "Peppermint tea may reduce symptoms of irritable bowel syndrome like gas",
    "Drinking chamomile tea before meals and at bedtime may reduce symptoms",
    "Activated charcoal also helps eliminate gas trapped in your colon(take tablets right before and one hour after meals)",
    "Dilute a tablespoon of apple cider vinegar in water or tea and drink right before meals or upto three times daily as long as need to reduce symptoms"],

  "Constipation": ["Drink more water", "Eat more fibre which are soluble and non-fermentable fibres as people who   are constipated are often told to increase their fibre intake because increasing fibre intake is thought to increase the bulk and consistency of bowel movements making them easier to pass",
    "Exercise more as it seems to reduce some symptoms of constipation",
    "Drink coffee(especially caffeinated coffee) as it can stimulate the muscles of intestine and  the urge to go to bathroom",
    "Probiotics may also help prevent chronic constipation",
    "Eat prebiotic fibres as they improve digestive health by feeding the friendly bacteria in your gut", "Avoid dairy products"],

  "Malaria": ["Apple cider vinegar mixed with water and soaked in a towel and kept on calves for 10 to 12 minutes helps",
    "Boil ginger in water and drink one to two cups on a daily basis",
    "Boil cinnamon and pepper powder in water and add honey to the strained water and drink it one to two times a day",
    "Consume two to three glasses of orange juice or grapefruit juice on a daily basis",
    "Have two cups of herbal tea or turmeric milk everyday"],

  "Dengue": ["Boil two small stems of Giloy plant in a glass of water and consume this water when it is little warm",
    "You can also add few drops of giloy juice to a cup of boiled water and drink this twice a day",
    "Papaya leaf juice is a great remedy to increase platelet count and it also improves immunity which helps in treating dengue",
    "You can also drink fresh guava juice for relief from dengue",
    "Fenugreek seeds are also rich in multiple nutrients which help in controlling dengue fever",
    "Add immunity boosting foods to your diet like citrus foods(eg. garlic, almonds, turmeric and many more..)"],

  "Hypertension": ["Walk and exercise regularly", "Reduce your sodium intake mainly salt",
    "Avoid processed food as they contain large sodium", "Drink less alcohol as alcohol may elevate the blood pressure",
    "Eat more potassium rich food(ie. leafy vegetables tomatoes, potatoes, sweet potatoes, melons, bananas, avocados, orangese, and apricots), Cutdown your caffeine(coffee) intake",
    "Learn to manage stress as stress is the key driver of high blood pressure", "Eat dark chocolate or cocoa",
    "If you are overweight then losing weight can make a big difference for your heart health", "Quit smoking",
    "Reduce intake of added sugar and refined carbs"],

  "Stress": ["Daily exercise will help you to reduce your stress", "Meditation is also a powerful way to reduce stress",
    "Perform relaxation exercises", "Some research suggest that journaling and other form of writing can help people to cope better with anxiety",
    "Try to make better strategies for your time management",
    "Aroma Therapy ie. smelling soothing plants oils can help to ease stress and anxiety",
    "Herbal teas also help with anxiety and ease sleep", "Spending time with animals can also help in reducing stress"],

  "Panic Attacks": ["Regular exercise will help to reduce your stress", "If you smoke or consume alcohol then you should stop doing so",
    "If you have chronic anxiety then caffeine is not your friend and you should stop consuming caffeine",
    "Get some good sleep", "You should start meditation also as meditation is a very good way to reduce stress and panic attacks",
    "Eat a healthy diet", "Practice deep breathing", "You may also try aroma therapy ie. smelling flower oils may help you",
    "Drink chamomile tea as it will calm frayed nerves and promote sleep"],

  "Chicken Pox": ["Apply calamine lotion as it contains zinc oxide which helps in reducing itching",
    "If chickenpox has also appeared inside your mouth then encouraging to suck on sugar free popsicles can be a good way to soothe mouth sores", "Oatmeal baths can be soothing and itch relieving for chickenpox as taking a bath won’t spread the chickenpox from one are of your skin to another",
    "Wear mittens to prevent scratching",
    "Add one cup of baking soda to a shallow luke warm water and  bath for 15-20 minutes for two to three times a day",
    "Use chamomile compresses", "Give approved pain relievers"],

  "Measles": ["a measles vaccine given within 72 hours of exposure can give relief",
    "a dose of immune proteins called immunoglobulin, taken within six days of exposure can also give relief",
    "rest to help boost your immune system",
    "drink plenty of fluids",
    "a humidifier to ease a cough and sore throat",
    "one can also take vitamin A supplements"],

  "Mumps": ["a warm or cold compress to ease pain and tenderness",
    "consuming foods that do not need chewing such as soups, mashed vegetables, or oatmeal",
    "avoiding sour foods such as citrus fruits, as these can stimulate saliva production",
    "If the patient experiences a fever of 103 degrees Fahrenheit or 39 degrees Celsius or above, confusion or disorientation, pain in the abdomen or testicles, or difficulty eating or drinking, medical help should be sought"],

  "Cellulitis": ["Properly covering the affected skin will help it heal and prevent irritation",
    "Follow proper instructions for dressing your wound and be sure to change your bandage regularly",
    "Follow proper recommendations for cleaning the affected skin",
    "Elevating the affected area ie. if your leg is affected, lie down and elevate your leg above your heart. This will help reduce swelling and ease your pain",
    "If the affected skin is hot and painful, apply a clean washcloth soaked in cool water but avoid chemical ice packs, as these can further irritate damaged skin",
    "A nonsteroidal anti-inflammatory, like ibuprofen (Advil, Motrin) or naproxen (Aleve), can help reduce pain and inflammation",
    "Treat any underlying conditions, such as athlete’s foot or eczema, that caused the wound that got infected",
    "If you are taking antibiotics, take antibiotics till you are completely cured otherwise it may come back and the second course of antibiotics may not be as effective as the first"],

  "Dermatitis": ["Moisturize your skin as routinely applying a moisturizer with high oil content can help your skin",
    "Use nonprescription anti-inflammation and anti-itch products",
    "Apply a cool wet cloth. This helps soothe your skin",
    "Take a comfortably warm bath, Sprinkle your bath water with baking soda or colloidal oatmeal — a finely ground oatmeal that's made for the bathtub. Soak for 5 to 10 minutes, pat dry and apply unscented moisturizer while your skin is still damp",
    "A lotion of 12 percent ammonium lactate or 10 percent alpha-hydroxy acid helps with flaky, dry skin",
    "For dandruff, use OTC shampoos containing selenium sulfide, zinc pyrithione, coal tar or ketoconazole",
    "Take a dilute bleach bath. This may help people with severe atopic dermatitis by decreasing the bacteria on the skin",
    "Avoid rubbing and scratching. Cover the itchy area with a dressing if you can't keep from scratching it",
    "Trim your nails and wear gloves at night, Wear cotton clothing",
    "Smooth-textured cotton clothing can help you avoid irritating the affected area",
    "Avoid wool, as itching can flare after removing wool clothing that directly touches the skin, Choose mild laundry detergent",
    "Emotional stressors can cause some types of dermatitis to flare up. Consider trying stress management techniques such as relaxation or biofeedback"],

  "Acne": ["Apply Apple Cider Vinegar",
    "Take a Zinc Supplement",
    "Make a Honey and Cinnamon Mask",
    "Spot Treat With Tea Tree Oil",
    "Apply Green Tea to Your Skin",
    "Apply Witch Hazel as Witch hazel is extracted from the bark and leaves of the North American witch hazel shrub",
    "Moisturize With Aloe Vera",
    "Take a Fish Oil Supplement as Omega-3 fatty acids are incredibly healthy fats that offer a multitude of health benefits",
    "Exfoliate Regularly ie Exfoliation is the process of removing the top layer of dead skin cells. It can be achieved mechanically by using a brush or scrub to physically remove the cells",
    "Cut Back on Dairy as The relationship between dairy and acne is highly controversial. Drinking milk and consuming dairy products exposes you to hormones, which may cause hormonal changes and lead to acne",
    "Reduce Stress as The hormones released during periods of stress may increase sebum production and skin inflammation, making acne worse",
    "Exercise Regularly"],

  "Insomnia":["Mindfulness meditation: It consists of slow, steady breathing while sitting quietly. You observe your breath, body, thoughts, feelings, and sensations as they rise and pass.",
    "Mantra repetition: Repeating a mantra or positive affirmation repeatedly can help focus and calm your mind. Mantras are said to produce feelings of relaxation by quieting the mind",
    "Yoga has been found to have a positive effect on sleep quality. Yoga may also alleviate stress, improve physical functioning, and boost mental focus.",
    "Exercise boosts overall health. It can enhance your mood, give you more energy, aid in weight loss, and promote better sleep.",
    "Massage therapy may benefit people with insomnia by improving sleep quality and daytime dysfunction. It may also reduce feelings of pain, anxiety, and depression.",
    "Lavender oil:Lavender is used to improve mood, reduce pain, and promote sleep. Taking it orally is thought to be more effective."],

  "Sleep Apnea":["Maintain a healthy weight Doctors commonly recommend people with sleep apnea to lose weight. Obesity, specifically in the upper body, can increase the risk of airway obstruction and narrow nasal passages. These obstructions can cause you to stop breathing suddenly or for lengths of time while sleeping.",
    "Try yoga ,regular exercise can increase your energy level, strengthen your heart, and improve sleep apnea.",
    "Alter your sleep position. Though a small change, altering your sleep position can reduce sleep apnea symptoms and improve your night’s rest.",
    "Use a humidifier Humidifiers are devices that add moisture to the air. Dry air can irritate the body and the respiratory system. Using a humidifier can open your airways, decrease congestion, and encourage clearer breathing.",
    "Avoid alcohol and smoking Lifestyle changes can improve your health and encourage better sleeping habits. Consider quitting smoking and limiting your alcohol intake to reduce sleep apnea complications.",
    "Use oral appliances. Oral appliances can help with sleep apnea by repositioning your jaw or tongue to keep your airway open while you sleep."],

  "Hyperthyroidism":["a","b","c","d","e"],

  "Hypothyroidism":["Iodine is important if your thyroid is underactive. On average you only need about 150 mcg of iodine a day from your diet. Before taking iodine supplements you should check if you are deficient in this mineral as too much could have the opposite effect on your thyroid.",
    "Panax or Korean Ginseng is a dried root herb that has positive benefits on the production of thyroid hormones and for those people with hypothyroidism",
    "Ginger is a great source of magnesium, zinc, and potassium, all of which are important for the thyroid",
    "Echinacea is a great herb for those with an overactive thyroid such as Graves disease and even underactive Hashimoto’s disease.",
    "Nettle, sometimes called a “thyroid tonic” because it can help balance both an overactive thyroid and an underactive thyroid.",
    "Ashwagandha is an Ayurvedic herb used for many centuries for its numerous healing benefits. One of its advantages as a natural remedy for hypothyroidism is its action to produce the T4 hormone",
    "Turmeric is one of my favorite herbs as it provides tremendous health benefits for the prevention of disease and cancer risks"],

  "Kidney stones":["Drink plenty of water because when passing a stone, upping your water intake can help speed up the process. Strive for 12 glasses of water per day instead of the usual 8.",
    "Lemon juice You can add freshly squeezed lemons to your water as often as you like. Lemons contain citrate, which is a chemical that prevents calcium stones from forming. Citrates can also break up small stones, allowing them to pass more easily.",
    "Basil juice as basil contains acetic acid, which helps to break down the kidney stones and reduce pain. It’s also full of nutrients. This remedy has been used traditionally for digestive and inflammatory disorders. There are antioxidants and anti-inflammatory agents in basil juice, and it may be helpful in maintaining kidney health.",
    "Apple cider vinegar as it  contains acetic acid. Acetic acid helps to dissolve kidney stones. In addition to flushing out the kidneys, apple cider vinegar can help ease pain caused by the stones.",
    "Celery juice as it is thought to clear away toxins that contribute to kidney stone formation and has long been used in traditional medications. It also helps flush out the body so you can pass the stone.",
    "Pomegranate juice has been used for centuries to improve overall kidney function. It will flush stones and other toxins from your system",
    "Kidney bean broth or broth from cooked kidney beans has been used to improve overall urinary and kidney health. It also helps dissolve and flush out the stones"],

  "Urinary Tract Infection":["Drink Plenty of Fluids. Hydration status has been linked to the risk of urinary tract infection. This is because regular urination can help flush bacteria from the urinary tract to prevent infection",
    "Increase Vitamin C Intake, Drink Unsweetened Cranberry Juice. Drinking unsweetened cranberry juice is one of the most well-known natural remedies for urinary tract infections",
    "Take Probiotics. Probiotics are beneficial microorganisms that are consumed through food or supplements. They can promote a healthy balance of bacteria in your gut.",
    "It's important not to hold urine for too long. This can lead to a buildup of bacteria, resulting in infection",
    "Peeing after sexual intercourse can also reduce the risk of UTIs by preventing the spread of bacteria",
    "Those who are prone to UTIs should avoid using spermicide, since it has been linked to an increase in UTIs",
    "Finally, when you use the toilet, make sure you wipe front to back. Wiping from back to front can cause bacteria to spread to the urinary tract and is associated with an increased risk of UTIs",
    "Garlic has been shown to have antimicrobial properties and may be able to block the growth of bacteria to prevent UTIs"]
}
