module.exports = {
  "Influenza": ["getting a shot of flue vaccine each flue season is the best thing one can do to protect himself",
    "Avoid close contact with those who are sick or other people if you are sick",
    "you have flu-like symptoms, stay home from school or work for at least 24 hours after your fever has disappeared",
    "use a tissue to cover your nose and mouth when sneezing and coughing. Dispose of the tissue immediately after use",
    "regularly wash your hands with soap and water or an alcohol-based hand rub",
    "try not to touch your eyes, nose, or mouth without first washing your hands to ensure they are germ-free",
    "cean and disinfect surfaces that people come into contact with at work, school, or home",
    "maintain your immune system by eating healthy fruits and vegetables, exercising daily, reduce stress and taking sleep of 7 to 9 hours each night",
    "if your are a smoker, just quit smoking"],

  "Common Cold": ["washing your hands frequently is probably single best measure to prevent cold from spreading",
    "Avoid touching your face, especially the nose, mouth, and eye areas, if you are around someone with a cold or have been touching surfaces in a public area",
    "Don't smoke as cigarette smoke can irritate the airways and increase susceptibility to colds and other infections",
    "Use disposable items if someone in your family is infected. Disposable cups can be thrown away after each use and prevent accidental spread of the virus from sharing of cups or glasses",
    "Keep household surfaces clean eg. door knobs, drawer pulls, keyboards, light switches, telephones, remote controls, countertops, and sinks can all harbor viruses for hours after their use by an infected person",
    "If your child has a cold, wash his or her toys as well when you are cleaning household surfaces and commonly-used items",
    "Use paper towels in the kitchen and bathroom for hand washing. Germs can live for several hours on cloth towels. Alternatively, have separate towels for each family member and provide a clean one for guests",
    "Control stress as studies have shown that people experiencing emotional stress have weakened immune systems and are more likely to catch a cold than their calmer counterparts"],

  "Pneumonia": ["Get Pneumonia vaccine as it reduces the risk of getting Pneumonia",
    "Avoid smoking as smoking makes your immune system weak",
    "Wash your hands often in warm, soapy water",
    "Use an alcohol-based hand sanitizer when you can’t wash your hands",
    "Avoid exposure to people who are ill whenever possible",
    "Get enough rest and sleep. This will boost your immnune system",
    "Eat a healthy diet that includes lots of fruits, vegetables, fiber, and lean protein"],

  "Diarrhoea": ["Drink only bottled water, even for tooth brushing",
    "Avoid eating food from street vendors",
    "Avoid ice made with tap water",
    "Eat only those fruits or vegetables that are cooked or can be peeled",
    "Be sure that all foods you eat are thoroughly cooked and served steaming hot",
    "Never eat raw or undercooked meat or seafood",
    "Obtain hepatitis A and typhoid vaccinations prior to travel, if indicated for that region"],

  "Indigestion": ["Do not chew with your mouth open, talk while chewing, or eat quickly",
    "Chew food completely and eat slowly",
    "Drink fluids after meals, rather than during",
    "Avoid late-night eating",
    "Avoid too much spicy, greasy foods",
    "If you are a smoker, quit smoking",
    "Avoid alcoholic beverages"],

  "Intestinal Gas": ["Eat smaller but more frequent meals. If you often suffer from indigestion, have five to six smaller meals a day, rather than three square meals",
    "Eat on time and avoid skipping meals",
    "Consume less irritating fo​ods",
    "Drink alcohol in moderation",
    "If your are a smoker, quit smoking",
    "Better manage your stress"],

  "Constipation": ["drink plenty of water (6–8 glasses per day)",
    "increase your fibre intake with foods such as wholegrain breads, fresh fruits, prune juice (natural laxative)",
    "limit intake of junk food",
    "exercise regularly",
    "go to the toilet when you feel the need",
    "take medication only as directed",
    "get your clinician or pharmacist to check the medications you take"],

  "Malaria": ["Applying mosquito repellents. Remember to reapply it frequently",
    "Always using mosquito nets over the bed",
    "Wear long sleeves clothes that cover your arms and legs completely",
    "Screen your doors and windows, especially during the evenings",
    "Opt for loose-fitted clothes instead of tight ones",
    "Stay indoors during the evenings",
    "You should also keep your fan on at night"],

  "Dengue": ["Reduce the amount of skin exposed by wearing long pants, long-sleeved shirts, and socks, tucking pant legs into shoes or socks, and wearing a hat",
    "Use a mosquito repellent with at least 10 percent concentration of diethyltoluamide (DEET), or a higher concentration for longer lengths of exposure. Avoid using DEET on young children",
    "Use mosquito traps and nets. Nets treated with insecticide are more effective, otherwise the mosquito can bite through the net if the person is standing next to it. The insecticide will kill mosquitoes and other insects, and it will repel insects from entering the room",
    "Structural barriers, such as screens or netting on doors and windows, can keep mosquitos out",
    "Avoid scents as heavily scented soaps and perfumes may attract mosquitos",
    "Treat clothes, shoes, and camping gear with permethrin, or purchase clothes that have been pretreated",
    "Try to avoid being outside at dawn, dusk, and early evening",
    "The Aedes mosquito breeds in clean, stagnant water. Checking for and removing stagnant water can help reduce the risk",
    "To reduce the risk of mosquitoes breeding in stagnant water: turn buckets and watering cans over and store them under shelter so that water cannot accumulate, remove excess water from plant pot plates, scrub containers to remove mosquito eggs, loosen soil from potted plants, to prevent puddles forming on the surface",
    "When camping or picnicking, choose an area that is away from still water"],

  "Hypertension": [" Lose extra pounds and watch your waistline as blood pressure often increases as weight increases",
    "Exercise regularly. Regular physical activity — such as 150 minutes a week, or about 30 minutes most days of the week — can lower your blood pressure by about 5 to 8 mm Hg if you have high blood pressure. It's important to be consistent because if you stop exercising, your blood pressure can rise again",
    "Eat a healthy diet. Eating a diet that is rich in whole grains, fruits, vegetables and low-fat dairy products and skimps on saturated fat and cholesterol can lower your blood pressure",
    "Reduce sodium in your diet. Even a small reduction in the sodium in your diet can improve your heart health and reduce blood pressure",
    "Limit the amount of alcohol you drink",
    "Quit smoking. Each cigarette you smoke increases your blood pressure for many minutes after you finish",
    "Cut back on caffeine. The role caffeine plays in blood pressure is still debated. Caffeine can raise blood pressure",
    "Reduce your stress. Chronic stress may contribute to high blood pressure",
    "Monitor your blood pressure at home and see your doctor regularly"],

  "Stress": ["Keep a positive attitude",
    "Accept that there are events that you cannot control",
    "Be assertive instead of aggressive",
    "Learn and practice relaxation techniques; try meditation, yoga, or tai-chi for stress management",
    "Exercise regularly",
    "Eat healthy, well-balanced meals"],

  "Panic Attacks": ["Use deep breathing",
    "Recognize that you’re having a panic attack",
    "Some panic attacks come from triggers that overwhelm you. If you’re in a fast-paced environment with a lot of stimuli, this can feed your panic attack. To reduce the stimuli, close your eyes during your panic attack",
    "Remind yourself that panic attacks always end",
    "Use muscle relaxation techniques. Much like deep breathing, muscle relaxation techniques can help stop your panic attack in its tracks by controlling your body’s response as much as possible",
    "Try to picture your happy face"],

  "Chicken Pox": ["First and the best way to prevent chickenpox is to get a chickenpox vaccine",
    "Stay away from a person if he is suffering from chickenpox",
    "Take care of your hygiene"],

  "Measles": ["Taking MMR vaccine reduces the risk of measles significantly",
    "Measles is a highly preventable disease because of the effectiveness of the MMR (mumps, measles, and rubella) vaccine. Children are usually vaccinated against mumps between 12 and 15 months of age and then again between the ages of 4 and 6"],

  "Mumps": ["Mumps is a highly preventable disease because of the effectiveness of the MMR (mumps, measles, and rubella) vaccine. Children are usually vaccinated against mumps between 12 and 15 months of age and then again between the ages of 4 and 6",
    "The MMR vaccine is very safe and effective. A single dose of the vaccine provides long-lasting immunity. The most common adverse events following the MMR vaccine are pain where the vaccine is given, fever, a mild rash, and swollen glands in the cheeks or neck"],

  "Cellulitis": ["Wash your wound daily with soap and water. Do this gently as part of your normal bathing",
    "Apply a protective cream or ointment",
    "Cover your wound with a bandage",
    "Watch for signs of infection"],

  "Dermatitis": ["Use a humidifier at home and at work to keep the air from getting too dry",
    "Wear loose-fitting, natural-fiber clothing; untreated cotton is ideal",
    "Avoid plated jewelry, especially in your ears, to prevent nickel-related rashes. Surgical steel or 14-karat gold earring posts are safer choices",
    "Don't wear a watchband that presses against your skin for long periods; the friction and sweat buildup can cause rashes",
    "Take warm, not hot, baths or showers and use mild soaps",
    "Lubricate your skin after a bath and several times during the day when possible using an unscented lotion or cream"],

  "Acne": ["Properly wash your face. To help prevent pimples, it's important to remove excess oil, dirt, and sweat daily",
    "Know your skin type. Anyone can get pimples, no matter their skin type",
    "Moisturize skin",
    "Use over-the-counter acne treatments",
    "Stay hydrated",
    "Limit makeup",
    "Don't touch your face",
    "Limit sun exposure",
    "If you have some pimples on your face, don't pop them as this will make the problem worse only",
    "Use antibiotics. They may be applied topically to your skin or taken by mouth"],

  "Insomnia": ["Think positive",
    "Try to go to sleep at the same time each night and get up at the same time each morning",
    "Avoid caffeine, nicotine, and alcohol late in the day",
    "Get regular exercise",
    "Don't eat a heavy meal late in the day",
    "Make your sleeping place comfortable"],

  "Sleep Apnea": ["Maintain a healthy weight. Doctors commonly recommend people with sleep apnea to lose weight",
    "Try yoga. Regular exercise can increase your energy level, strengthen your heart, and improve sleep apnea",
    "Alter your sleep position",
    "Use a humidifier",
    "Avoid alcohol and smoking",
    "Use oral appliances. Oral appliances can help with sleep apnea by repositioning your jaw or tongue to keep your airway open while you sleep"],

  "Hyperthyroidism": ["Diet is important factor. Keep a tab on your food intake. A balanced and utterly nutritious diet not only helps you to stay healthy but also takes care of all sorts of hormonal secretions",
    "Avoid processed food. Processed and packed foods are not only threatening to your weight but also can be a disaster for various health goals",
    "Defiance of iodine is one of the primary reasons for thyroid issues across the world. Supplements can be taken, and in many countries, it is done with the iodized table salt and dairy foods. However, too much of iodine can lead to hyperthyroidism",
    "If you are all for taking iodine pills, then you should first consult a doctor. Thyroid health can be maintained by taking Vitamin D or selenium",
    "Thyroid problems can be treated with ease when found early. Always seek doctor’s advice before you try any medicine for your health problems related to thyroid"],

  "Hypothyroidism": ["Hypothyroidism is very hard prevented. The best way to prevent developing a serious form of the condition or having the symptoms impact your life in a serious way is to watch for signs of hypothyroidism",
    "If you experience any of the symptoms of hypothyroidism, the best thing to do is talk to your healthcare provider",
    "Hypothyroidism is very manageable if you catch it early and begin treatment"],

  "Kidney Stones": ["Stay hydrated, drinks lots of fluid",
    "Eat more calcium-rich foods",
    "Eat less sodium",
    "Eat fewer oxalate-rich foods",
    "Eat less animal protein",
    "Avoid vitamin C supplements",
    "Explore herbal remedies",
    "Talk to your doctor about the medications you’re currently taking"],

  "Urinary Tract Infection": ["Drink plenty of water, and relieve yourself often. The simplest way to prevent a UTI is to flush bacteria out of the bladder and urinary tract before it can set in. If you’re well-hydrated, it will be tough to go too long without urinating",
    "Wipe from front to back. Bacteria tend to hang around the anus. If you wipe from front to back, especially after a bowel movement, they're less likely to make it to the urethra",
    "Wash up before sex and urinate after it. Use soap and water before sex. This keeps bacteria away from the urethra. And urinating afterward pushes any bacteria that entered the urinary tract back out",
    "Steer clear of irritating feminine products. Skip douches, deodorant sprays, scented powders, and other potentially irritating feminine products",
    "Rethink your birth control. A diaphragm, spermicide, or spermicide-lubricated condom can make you more likely to get a UTI because they all can contribute to bacterial growth. If you often get UTIs and use one of these birth control methods, switch to a water-based lubricant for vaginal dryness, and consider trying another birth control method to see if it helps"]
}
